spring:
  application:
    name: springBootLogback
#  zipkin:
#    baseUrl: http://localhost:9411/zipkin/
  datasource:
    max-idle: 10
    password: root
    validationQuery: SELECT 1
    testOnBorrow: true
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    max-active: 15
    driverClassName: com.mysql.jdbc.Driver
    max-wait: 8000
#    url: jdbc:mysql://localhost:3306/images?autoreconnect=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/seckill?autoreconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root





  redis:
    sentinel:
      master: master
      nodes: 81.71.16.134:6379,81.71.16.134:6380,81.71.16.134:6381
    password: redis

  devtools:
    restart:
      enabled: false


server:
  port: 8090
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
  user:
    password: root
    name: root
#Zipkin-export: true
#
#flyway:
#  password: root
#  schemas: cbank
#  sql-migration-prefix: V
#  locations: db/migration
#  encoding: UTF-8
#  user: root
#  enabled: false
#  url: jdbc:mysql://localhost:3306/mysql
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false


#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
flyway:
  enabled: false





# mybatis-plus config
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yudianxx.web.mapper.**
  global-config:
    db-config:
      db-type: mysql
      id-type: auto
  #      table-underline: false
  configuration:
    map-underscore-to-camel-case: true


logging:
  config: classpath:logback.xml
  level:
    com.yudianxx.springBootDemo: info

create:
  bean: myBean

